### ISSUE TITLE
Shenandoah GC not available on GraalVM 21/22

### ISSUE THREAD

**Issue by kamild1996** [Mukul1127/Minecraft-Java-Flags#1]
On GraalVM 21 and 22 (other versions untested), attempts at using Shenandoah GC end with the following error:
```
Error occurred during initialization of VM
Option -XX:+UseShenandoahGC not supported
```

Having this mentioned in the guide (https://github.com/Mukul1127/Minecraft-Java-Flags#shenandoah) would be great.

**Comment by Mukul1127** [comment]
This is expected, I will fix the guide with a notice
