### ISSUE TITLE
Birdflop recommended [server] flags

### ISSUE THREAD

**Issue by sudosign** [Mukul1127/Minecraft-Java-Flags#3]
https://www.birdflop.com/resources/flags/ not sure if they are good or not but maybe like look through and see if they match up

**Comment by Mukul1127** [comment]
This website seems to just make a script for you including java arguments and some nice to haves.

Breakdown of flags to choose from:
 - Aikar's Flags - https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/ TLDR: Great flags that the server G1GC arguments are based off of.
 - Benchmarked ones - @brucethemoose's repo
 - Hilltty's Flags - idk, never heard of him, juts uses Large Pages, Shenandoah, and some other flags
 - Obydux's Flags - This seems to be GraalVM optimized for Pufferfish server??? Don't think any other server benefits from `--add-modules=jdk.incubator.vector`
 - Etil's Flags - Used in this guide
 - Proxy - Minimal but nothing too special
